import React, { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'en' | 'es' | 'pl' | 'zh';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

// Translations dictionary
const translations: Record<Language, Record<string, string>> = {
    en: {
        welcome: 'Welcome to GlassBank',
        getStarted: 'Get Started',
        selectLanguage: 'Select Your Language',
        english: 'English',
        spanish: 'Español',
        polish: 'Polski',
        mandarin: '中文',
        continue: 'Continue',
        back: 'Back',
        home: 'Home',
        transactions: 'Transactions',
        cards: 'Cards',
        automations: 'Automations',
        more: 'More',
        balance: 'Balance',
        sendMoney: 'Send Money',
        payBill: 'Pay Bill',
        addMoney: 'Add Money',
        viewCards: 'Cards',
        recentTransactions: 'Recent Transactions',
        seeAll: 'See All',
        thisMonth: 'This Month',
        spending: 'Spending',
        remaining: 'Remaining',
        uploadID: 'Upload Your ID',
        frontOfID: 'Front of ID',
        backOfID: 'Back of ID',
        takeSelfie: 'Take a Selfie',
        verifying: 'Verifying Your Identity',
        verified: 'You\'re Verified!',
        setupAccount: 'Set Up Your Account',
        createPin: 'Create a PIN',
        confirmPin: 'Confirm PIN',
        whatsNew: 'What\'s New',
        skipTour: 'Skip Tour',
        gotIt: 'Got It',
        next: 'Next',
        settings: 'Settings',
        notifications: 'Notifications',
        profile: 'Profile',
        security: 'Security',
        language: 'Language',
        accessibilityMode: 'Accessibility Mode',
        standard: 'Standard',
        simplified: 'Simplified',
        createAutomation: 'Create Automation',
        recurringPayment: 'Recurring Payment',
        scheduledTransfer: 'Scheduled Transfer',
        roundUp: 'Round-Up Savings',
        dispute: 'Dispute Transaction',
        reportIssue: 'Report an Issue',
    },
    es: {
        welcome: 'Bienvenido a GlassBank',
        getStarted: 'Comenzar',
        selectLanguage: 'Selecciona Tu Idioma',
        english: 'English',
        spanish: 'Español',
        polish: 'Polski',
        mandarin: '中文',
        continue: 'Continuar',
        back: 'Atrás',
        home: 'Inicio',
        transactions: 'Transacciones',
        cards: 'Tarjetas',
        automations: 'Automatizaciones',
        more: 'Más',
        balance: 'Saldo',
        sendMoney: 'Enviar Dinero',
        payBill: 'Pagar Factura',
        addMoney: 'Agregar Dinero',
        viewCards: 'Tarjetas',
        recentTransactions: 'Transacciones Recientes',
        seeAll: 'Ver Todo',
        thisMonth: 'Este Mes',
        spending: 'Gastos',
        remaining: 'Restante',
        uploadID: 'Sube Tu Identificación',
        frontOfID: 'Frente de ID',
        backOfID: 'Reverso de ID',
        takeSelfie: 'Tomar una Selfie',
        verifying: 'Verificando Tu Identidad',
        verified: '¡Estás Verificado!',
        setupAccount: 'Configura Tu Cuenta',
        createPin: 'Crear un PIN',
        confirmPin: 'Confirmar PIN',
        whatsNew: 'Novedades',
        skipTour: 'Saltar Tour',
        gotIt: 'Entendido',
        next: 'Siguiente',
        settings: 'Configuración',
        notifications: 'Notificaciones',
        profile: 'Perfil',
        security: 'Seguridad',
        language: 'Idioma',
        accessibilityMode: 'Modo de Accesibilidad',
        standard: 'Estándar',
        simplified: 'Simplificado',
        createAutomation: 'Crear Automatización',
        recurringPayment: 'Pago Recurrente',
        scheduledTransfer: 'Transferencia Programada',
        roundUp: 'Ahorro con Redondeo',
        dispute: 'Disputar Transacción',
        reportIssue: 'Reportar un Problema',
    },
    pl: {
        welcome: 'Witamy w GlassBank',
        getStarted: 'Rozpocznij',
        selectLanguage: 'Wybierz Swój Język',
        english: 'English',
        spanish: 'Español',
        polish: 'Polski',
        mandarin: '中文',
        continue: 'Kontynuuj',
        back: 'Wstecz',
        home: 'Główna',
        transactions: 'Transakcje',
        cards: 'Karty',
        automations: 'Automatyzacje',
        more: 'Więcej',
        balance: 'Saldo',
        sendMoney: 'Wyślij Pieniądze',
        payBill: 'Zapłać Rachunek',
        addMoney: 'Dodaj Pieniądze',
        viewCards: 'Karty',
        recentTransactions: 'Ostatnie Transakcje',
        seeAll: 'Zobacz Wszystko',
        thisMonth: 'Ten Miesiąc',
        spending: 'Wydatki',
        remaining: 'Pozostało',
        uploadID: 'Prześlij Dokument Tożsamości',
        frontOfID: 'Przód Dokumentu',
        backOfID: 'Tył Dokumentu',
        takeSelfie: 'Zrób Selfie',
        verifying: 'Weryfikacja Tożsamości',
        verified: 'Jesteś Zweryfikowany!',
        setupAccount: 'Skonfiguruj Konto',
        createPin: 'Utwórz PIN',
        confirmPin: 'Potwierdź PIN',
        whatsNew: 'Co Nowego',
        skipTour: 'Pomiń',
        gotIt: 'Rozumiem',
        next: 'Dalej',
        settings: 'Ustawienia',
        notifications: 'Powiadomienia',
        profile: 'Profil',
        security: 'Bezpieczeństwo',
        language: 'Język',
        accessibilityMode: 'Tryb Dostępności',
        standard: 'Standardowy',
        simplified: 'Uproszczony',
        createAutomation: 'Utwórz Automatyzację',
        recurringPayment: 'Płatność Cykliczna',
        scheduledTransfer: 'Zaplanowany Przelew',
        roundUp: 'Oszczędzanie z Zaokrągleniem',
        dispute: 'Reklamacja Transakcji',
        reportIssue: 'Zgłoś Problem',
    },
    zh: {
        welcome: '欢迎来到 GlassBank',
        getStarted: '开始使用',
        selectLanguage: '选择您的语言',
        english: 'English',
        spanish: 'Español',
        polish: 'Polski',
        mandarin: '中文',
        continue: '继续',
        back: '返回',
        home: '首页',
        transactions: '交易',
        cards: '银行卡',
        automations: '自动化',
        more: '更多',
        balance: '余额',
        sendMoney: '转账',
        payBill: '付账单',
        addMoney: '存款',
        viewCards: '银行卡',
        recentTransactions: '最近交易',
        seeAll: '查看全部',
        thisMonth: '本月',
        spending: '支出',
        remaining: '剩余',
        uploadID: '上传您的身份证',
        frontOfID: '身份证正面',
        backOfID: '身份证背面',
        takeSelfie: '自拍',
        verifying: '正在验证您的身份',
        verified: '验证成功！',
        setupAccount: '设置您的账户',
        createPin: '创建 PIN 码',
        confirmPin: '确认 PIN 码',
        whatsNew: '新功能',
        skipTour: '跳过导览',
        gotIt: '知道了',
        next: '下一步',
        settings: '设置',
        notifications: '通知',
        profile: '个人资料',
        security: '安全',
        language: '语言',
        accessibilityMode: '无障碍模式',
        standard: '标准',
        simplified: '简化',
        createAutomation: '创建自动化',
        recurringPayment: '定期付款',
        scheduledTransfer: '定时转账',
        roundUp: '零钱储蓄',
        dispute: '交易争议',
        reportIssue: '报告问题',
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}

export const SUPPORTED_LANGUAGES: { code: Language; name: string; flag: string }[] = [
    { code: 'en', name: 'English', flag: '🇬🇧' },
    { code: 'es', name: 'Español', flag: '🇪🇸' },
    { code: 'pl', name: 'Polski', flag: '🇵🇱' },
    { code: 'zh', name: '中文', flag: '🇨🇳' },
];
